execute pathogen#infect()
set mouse=
set ttymouse=
syntax on
set ls=2

filetype plugin indent on
let g:terraform_align=1
let g:terraform_fold_sections=1
let g:terraform_fmt_on_save=1

colorscheme afterglow

" turn hybrid line numbers on
:set number relativenumber
:nmap <f4> :set relativenumber! number! <cr>

"Automatic toggling between line number modes
:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
:  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
:augroup END 
