set mouse=
set ttymouse=
syntax on
set ls=2

colorscheme dotshare

" turn hybrid line numbers on
:set number relativenumber
:nmap <f4> :set relativenumber! number! <cr>

"Automatic toggling between line number modes
:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
:  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
:augroup END 
